apiVersion: v1
kind: Secret
metadata:
  name: url-shortener-secret
type: Opaque
data:
  # example-secret-value encoded in base64
  REDIS_PASSWORD: ""  # Add base64 encoded password if needed

